config/routes.rb
DotastatsFinal::Application.routes.draw do
  resources :matches
  resources :player

  get '/player/matches/:steam_id/' => 'player#matches', as: :player_matches

  root :to => 'home#index'

  get ':page', to: 'static#show', as: :static, constraints: { page: /[a-zA-Z\-_\/]+/ }
end

app/models/match.rb
class Match < ActiveRecord::Base
  has_many :match_histories
  has_many :players, through: :match_histories, foreign_key: :steam_id

  include MyUtils

  serialize :players, JSON

  def self.new_set(matches_array)
    matches_array.each do |match_json|
      match = Matches.find_or_create_by(match_id: match_json[:match_id].to_i)
      match.attributes = MyUtils.hash_nonintersect_to_s(match_json, match.attributes)
      match.save
    end
  end
end

app/models/match_history.rb
class MatchHistory < ActiveRecord::Base
  belongs_to :player, foreign_key: :steam_id, primary_key: :steam_id
  belongs_to :match
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :match_histories, foreign_key: :steam_id, primary_key: :steam_id
  has_many :matches, through: :match_histories

  include MyUtils
  require 'open-uri'
  require 'json'

  ANON_STEAM_ID = 76561202255233023
  STEAM_IDS = "&steamids=" # comma delimited
  MY_DEV_KEY = "?key=EF42A5E508EA32500904F09903220E7D"
  GET_PLAYER_SUM_URL = "http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/"

  def self.get_player_info(steam_id)
    steam_id_64bit = MyUtils.to_64bit steam_id
    return Players.get_p(ANON_STEAM_ID) if steam_id_64bit == ANON_STEAM_ID
    response = JSON.parse(open(GET_PLAYER_SUM_URL+MY_DEV_KEY+STEAM_IDS+steam_id_64bit.to_s).read, :symbolize_names => true)[:response]
    player_info = response[:players][0]
    if !player_info.nil?
      return Players.get_p(player_info)
    end
  end

private
  def self.get_p(player_info)
    if player_info == ANON_STEAM_ID
      player = Players.find_or_create_by(steam_id: 76561202255233023, personaname: "Anonfag")
    else
      player = Players.find_or_create_by(steam_id: player_info[:steam_id].to_i)
      player.attributes = MyUtils.hash_nonintersect_to_s(player_info, player.attributes)
    end
    return player if player.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  include MyUtils
  require 'open-uri'
  require 'json'

  ANON_STEAM_ID = 76561202255233023
  STEAM_IDS = "&steamids=" # comma delimited
  MY_DEV_KEY = "?key=EF42A5E508EA32500904F09903220E7D"
  GET_PLAYER_SUM_URL = "http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/"

  #Views
  def index
    if params[:player_id]
      # Support login's later
    end
  end

  def show(player = nil)
    if player.nil?
      if params[:dotabuff_url].to_s.length == 0
        logger.error "url blank" ## Logic for blank url's
      else
        steamid = MyUtils.to_64bit(URI.parse(params[:dotabuff_url]).path.split('/').last.to_i)
        steamid = 76561202255233023 if steamid == 76561197960265728
        @player = get_player_info(steamid)
      end
    end
  end

  def matches
    @player = Player.find_by_steam_id(params[:steam_id])
    @matches = @player.matches
  end

  #Non-views
  def get_player_info(steamid)
    raise "steam_id not converted correct" if steamid < 76561197960265728
    if steamid == ANON_STEAM_ID
      player = Player.find_or_create_by(steam_id: 76561202255233023, personaname: "Anonymous")
    else
      player = Player.find_by_steam_id(steamid)
      if !player
        response = JSON.parse(open(GET_PLAYER_SUM_URL+MY_DEV_KEY+STEAM_IDS+steamid.to_s).read, :symbolize_names => true)[:response]
        player_info = response[:players][0]
        if !player_info.nil?
          player_info[:steam_id] = player_info[:steamid]
          player_info.delete :steamid
          player = Player.new(player_info)
          player.save
        else
          player = nil
        end
      end
      player
    end
  end

  def get_match_history(player_id)
    history = JSON.parse(open(GET_MATCH_HISTORY_URL+QUERY_KEY_START+MY_DEV_KEY+ACCOUNT_ID+MyUtils.to_32bit(self.steam_id).to_s).read, :symbolize_names => true)[:result]
    return Matches.new_set(result[:matches])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def show
    # Works with nested subfolders
    # binding.pry
    template = File.join(params[:controller], params[:page])
    render template
    rescue ActionView::MissingTemplate => e
      if e.message =~ %r{Missing template #{template}}
      raise ActionController::RoutingError, 'Not Found'
    else
      raise e
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/home/index.html.erb
<div class="row">
	<div class="small-3 small-centered columns">
		<h1> dotastats </h1>
	</div>
</div>
<div class="row collapse has-form">
	<div class="small-10 columns">
		<%= form_tag("/player/show", method: "get") do %>
		  <%= text_field_tag :dotabuff_url, '', placeholder: "dotabuff url"  %>
  </div>
  <div class="small-2 columns">
	  	<%= submit_tag "Search", class: "button postfix" %>
  </div>
		<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<div class="sticky" data-options="sticky_on: large">
	  	<nav class="top-bar" data-topbar>
	  	  <ul class="title-area">
	  	    <li class="name">
	  	      <h1><a href="/">dotastats</a></h1>
	  	    </li>
	  	  </ul>

	  	  <section class="top-bar-section">
	  	    <!-- Right Nav Section -->
	  	    <ul class="right">
	  	      <li class="has-dropdown">
	  	        <a href="#">Account options</a>
	  	        <ul class="dropdown">
	  	          <li><a href="#">First link in dropdown</a></li>
	  	        </ul>
	  	      </li>
	  	    </ul>

	  	    <!-- Left Nav Section -->
	  	    <!-- <ul class="left">
	  	      <li><a href="#">Left Nav Button</a></li>
	  	    </ul> -->
	  	  </section>
	  	</nav>
  	</div>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/matches/index.html.erb
<h1>Matches</h1>

app/views/matches/search.html.erb
Player#search
<h1>Find match by player</h1>

<%= form_tag("/matches/show", method: "get") do %>
  <%= label_tag(:dotabuff_url, "dotabuff.com url:") %>
  <%= text_field_tag(:dotabuff_url) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/matches/show.html.erb
<%= params.inspect %>
<% if !@match %>
	<h1>Match not found!</h1>
<% else %>
	<table>
		<thead>
			<tr>
				<th>Match <%= @match.match_id %></th>
			</tr>
		</thead>
		<tbody>
			<%= content_tag_for(:tr, @match_players) do |player| %>
				<td><%= player.personaname %></td>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/pages/about.html.erb
<% provide(:title, '') %>
<h1>About Us</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<% provide(:title, '') %>
<h1>Contact Us</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/privacy.html.erb
<% provide(:title, '') %>
<h1>Privacy Policy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/terms.html.erb
<% provide(:title, '') %>
<h1>Terms of Service</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/player/index.html.erb
<h1>Player</h1>

<%= form_tag("/player/show", method: "get") do %>
  <%= label_tag(:dotabuff_url, "dotabuff.com url:") %>
  <%= text_field_tag(:dotabuff_url) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/player/matches.html.erb
<div class="row">
	<% if !@matches %>
		<h1>No matches found!</h1>
	<% else %>
		<div class="large-3 columns"></div>
		<table class="large-12 columns">
			<tr>
				<td><h1>Player <%= @player.personaname %></h1></td>
			</tr>
			<% @matches.each do |match| %>
				<tr>
					<td><%= link_to match[:match_id].to_s, "/matches/#{match[:match_id]}" %></td>
				</tr>
			<% end %>
		</table>
	<% end %>
</div>

app/views/player/show.html.erb
<div class="row">
	<% if !@player %>
		<h1 class="large-12 columns">Player not found!</h1>
	<% else %>
		<table class="large-12 columns">
			<tr>
				<td><h1>Player <%= @player.personaname %></h1></td>
				<td><%= link_to 'Matches', player_matches_url(steam_id: @player.steam_id) %></td>
			</tr>
			<tr>
				<td>steam id:</td>
				<td><%= @player.steam_id %></td>
			</tr>
			<tr>
				<td>personaname:</td>
				<td><%= @player.personaname %></td>
			</tr>
			<tr>
				<td>profileurl:</td>
				<td><%= @player.profileurl %></td>
			</tr>
			<tr>
				<td>avatar:</td>
				<td><img src="<%= @player.avatar %>"></td>
			</tr>
			<tr>
				<td>avatarmedium:</td>
				<td><img src="<%= @player.avatarmedium %>"></td>
			</tr>
			<tr>
				<td>avatarfull:</td>
				<td><img src="<%= @player.avatarfull %>"></td>
			</tr>
			<tr>
				<td>personastate:</td>
				<td><%= @player.personastate %></td>
			</tr>
			<tr>
				<td>communityvisibilitystate:</td>
				<td><%= @player.communityvisibilitystate %></td>
			</tr>
			<tr>
				<td>profilestate:</td>
				<td><%= @player.profilestate %></td>
			</tr>
			<tr>
				<td>lastlogoff:</td>
				<td><%= @player.lastlogoff %></td>
			</tr>
			<tr>
				<td>realname:</td>
				<td><%= @player.realname %></td>
			</tr>
			<tr>
				<td>primaryclanid:</td>
				<td><%= @player.primaryclanid %></td>
			</tr>
			<tr>
				<td>timecreated:</td>
				<td><%= @player.timecreated %></td>
			</tr>
			<tr>
				<td>gameid:</td>
				<td><%= @player.gameid %></td>
			</tr>
			<tr>
				<td>gameserverip:</td>
				<td><%= @player.gameserverip %></td>
			</tr>
			<tr>
				<td>gameserversteamdid:</td>
				<td><%= @player.gameserversteamid %></td>
			</tr>
			<tr>
				<td>gameextrainfo:</td>
				<td><%= @player.gameextrainfo %></td>
			</tr>
			<tr>
				<td>loccountrycode:</td>
				<td><%= @player.loccountrycode %></td>
			</tr>
			<tr>
				<td>locstatecode:</td>
				<td><%= @player.locstatecode %></td>
			</tr>
			<tr>
				<td>loccityid:</td>
				<td><%= @player.loccityid %></td>
			</tr>
			<tr>
				<td>commentpermission:</td>
				<td><%= @player.commentpermission %></td>
			</tr>
		</table>
	<% end %>
</div>